### ISSUE TITLE
Atmos Spatial Audio 

### ISSUE THREAD

**Issue by akash329d** [rixtox/mp4dovi#3]
This is probably unrelated to the goal of this project, but I've been trying to figure out how to get quicktime to recognize EAC3 Atmos audio in ffmpeg exported mp4's. The only way I've been able to do it is use subler, I saw they added support here - https://bitbucket.org/galad87/subler/issues/451/support-for-new-tags-hdr-4k-dolby-vision. 

Was curious if there was a way to accomplish the same thing by simply modifying the file? Was wondering if you know of anyone who has done this or if I should just try and figure it out myself.

**Comment by rixtox** [comment]
I don't know much about it. Maybe you can try to mux it with Apple's official muxing tool like [`mediafilesegmenter`](https://developer.apple.com/documentation/http_live_streaming/about_apple_s_http_live_streaming_tools).

If you figured out the rules and able to provide samples, I can maybe look into how to make a tool for that.

**Comment by akash329d** [comment]
> I don't know much about it. Maybe you can try to mux it with Apple's official muxing tool like [`mediafilesegmenter`](https://developer.apple.com/documentation/http_live_streaming/about_apple_s_http_live_streaming_tools).
> 
> If you figured out the rules and able to provide samples, I can maybe look into how to make a tool for that.

Subler creates the cookie here : https://bitbucket.org/galad87/mp42foundation/src/e42154278f286b102f0eb47ddf15921c97ded223/MP42/MP42FormatUtilites.mm#lines-1167

There's some details on the structure here - https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p.pdf (pg 78)

However I'm having trouble figuring out where exactly the cookie should be inserted.

mediafilesegmenter could be useful, but it only takes in mp4's rather than mkv's (I'm trying to convert mkv's to quicktime compatible mp4's).

**Comment by rixtox** [comment]
It occurs to me more suitable for an issue to file to ffmpeg or whatever tool you used for muxing than creating specialized tool for it. This project is somehow different as many videos downloaded directly from vendor sites are tagged as dvhe. Thus making a specialized tool makes sense.

**Comment by akash329d** [comment]
Fair enough, makes sense to me. Thanks!
