### ISSUE TITLE
Docker pull unauthorized

### ISSUE THREAD

**Issue by kylesyx** [rixtox/mp4dovi#4]
请问一下大佬，我运行docker pull ghcr.io/rixtox/mp4dovi:0.1.1的时候，报错如下：Error response from daemon: Head https://ghcr.io/v2/rixtox/mp4dovi/manifests/0.1.1: unauthorized
这该怎么解决呀，研究了一晚上没结果求指点！

**Comment by rixtox** [comment]
我建議還是直接用編譯好的二進制吧

**Comment by kylesyx** [comment]
请问您说的是release里的压缩包吗？我下载了windows x64的版本，运行exe文件没有任何反应呀。

**Comment by kylesyx** [comment]
> 我建議還是直接用編譯好的二進制吧
请问您说的是release里的压缩包吗？我下载了windows x64的版本，运行exe文件没有任何反应呀。

**Comment by kylesyx** [comment]
> 我建議還是直接用編譯好的二進制吧

请问您说的是release里的压缩包吗？我下载了windows x64的版本，运行exe文件没有任何反应呀。

**Comment by rixtox** [comment]
因爲是命令行程序啊，你需要在命令行下用，沒有GUI界面的

**Comment by kylesyx** [comment]
> 因爲是命令行程序啊，你需要在命令行下用，沒有GUI界面的

明白了！我才知道mac上原来可以运行darwin版本，刚刚试了下搞定了，可以正常观看了！大佬你太强了我感动得流泪，研究了好久好久只有你这个办法有效，真的太强了！
