### ISSUE TITLE
Audio Header is Changed

### ISSUE THREAD

**Issue by perrinpagess** [rixtox/mp4dovi#7]
When running the command, the Audio along with the Video's fourcc are changed to "dvh1" making the audio unplayable. ffmpeg forces the video fourcc to be hev1, claiming mp4 container doesn't support dvh1, even though the mp4 input file fourcc was dvh1, so I can't add another audio track after running the command. I am using eac3 5.1 audio.

**Comment by rixtox** [comment]
I’m not so sure what you mean. Can you provide sample files and the commands you used?

**Comment by perrinpagess** [comment]
Sorry, this actually seems to be an issue with the tool I'm using to mux to mp4.

https://github.com/DolbyLaboratories/dlb_mp4base

I'll ask them to fix it instead. When I use their mp4muxer it gives the audio stream a 'dvhe' fourcc instead of eac3 and no codec information so your program misinterprets the audio as video. When using a sample with proper header, audio is untouched.

ffprobe says this:

`Stream #0:0[0x1](und): Video: hevc (Main 10) (dvhe / 0x65687664), yuv420p10le(pc), 3840x2160 [SAR 1:1 DAR 16:9], 15185 kb/s, 59.94 fps, 59.94 tbr, 60k tbn (default)`

`Stream #0:1[0x2](und): Audio: none (dvhe / 0x65687664), 48000 Hz, 5.1(side), 640 kb/s (default)`
